trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Install VS Code Extension Manager (vsce >= v2.26.1 needed) and dependencies
- script: |
    npm install -g @vscode/vsce
    npm install
  displayName: "Install vsce and dependencies"

# Publish
- task: AzureCLI@2
  displayName: "Publish The Only"
  inputs:
    azureSubscription: "the-only-publishing"
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      vsce publish --azure-credential